### PR TITLE
README: Make this more easy on the eyes

### PR DESCRIPTION
**Pull request by CFSworks**
Hey there! Do you guys need a hand?

I have a couple of physical MikroTik devices to test on as well - they don't actually authenticate at this time so that's probably what I'll be working on next.

Could you read over this README and make sure I have the right idea? Thanks!

### CODE REVIEW

**Comment by senorsmile** [comment]
Hi @CFSworks .  Thanks for the contribution.  We are in the early stages (obviously) and are currently using the code internally.  We intend to get things to a general point of stability (almost there) and will start announcing the project to a wider audience.  

With that said, it's great that you've found us.  

We do actually test against a vagrant image (see the Vagrantfile) and against the following hardware:
- rb750
- rb951
- rb2011

We have a staging environment that uses an rb2011 where we run all of our tests, and code review everything.  

Please try out everything, remark on anything that's broken and contribute back anything you think will be helpful.  We also intend to get a more comprehensive project outline, contributor guidelines, etc.  

One of us will review this PR shortly.

**Comment by CFSworks** [comment]
Hi Shaun!

That sounds good. More than happy to do whatever, although if you have a couple of outstanding issues, I'd be able to work through them faster if they were cataloged as Github issues.

I imagine, for example, the `mikrotik.py` module is deprecated/early experimentation. It also depends on `rosapi` which nothing else seems to. Should that be torn out?

**Comment by senorsmile** [comment]
Yeah, we ended up extending and heavily modifying the rosapi to fix bugs and just simply make it better.  It should probably be torn out.  

@zahodi let's go through our list of internal Jira tickets and transfer any that make sense to github issues.

**Review by senorsmile — APPROVED** [review]
LGTM.  @zahodi please review.

**Comment by zahodi** [comment]
@CFSworks thanks for writing up the README. Looks good.

**Comment by CFSworks** [comment]
Thank you! Note also that I have a "sandbox" branch in my fork. These are commits that haven't really made it into a PR yet. Feel free to cherry-pick anything you like from there.

**Comment by senorsmile** [comment]
Nice!  I did a quick look through, and it all looks like good contributions.  Feel free to make individual PR's from the commits.  After integ/staging tests pass on my end, and the a code review, I'll merge things as quickly as time permits.

**Pull request merged**
